#!/bin/bash

platform='unknown'
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='darwin'
fi

alias l='ls++'
#alias pf='prt-get search'
#alias pi='sudo prt-get depinst'
#alias pd='sudo pacman -R'
#alias pq='pacman -Qu'

if [[ $platform == 'linux' ]]; then
    alias pf='pacaur -Ss --color always'
    alias pi='pacaur -S'
    alias pd='pacaur -R'
    alias pq='pacaur -Qu'
elif [[ $platform == 'darwin' ]]; then
    alias pf='brew search'
    alias pi='brew install'
    alias pd='brew uninstall'
    alias pq='brew list'
fi

#alias yf='yaourt -Ss'
#alias yi='yaourt -S'
#alias yd='yaourt -R'
#alias yq='yaourt -Qu'

alias pu='sudo pacman -U'
alias nsa='sudo netctl stop-all && sudo netctl start'
alias ns='sudo netctl start'

if [[ $platform == 'linux' ]]; then
    alias m='sudo mount'
    alias um='sudo umount'
fi

alias sv='sudo vim -u /home/nuko/.vimrc'
alias wm='sudo wifi-menu'
alias cx='sudo chmod +x'
alias rp='LANG=ja_JP.UTF-8 wine ~/Dropbox/ANDY\ MENTE/rs346/rp.exe'
alias syss='sudo systemctl start'
alias syst='sudo systemctl stop'
alias syse='sudo systemctl enable'
alias sysd='sudo systemctl disable'
alias sst='systemctl status'
alias tmr='transmission-remote'
alias ta='transmission-remote -a'
alias tl='transmission-remote -l'
alias td='transmission-daemon -w /mnt/hdd/Transmission'
alias tmux='TERM=screen-256color-bce tmux'
alias syu='sudo pacman -Syu'
alias yg='yaourt -G'
alias en='LC_ALL=en_US.UTF-8'
alias ov='sudo openvpn --config /etc/openvpn/client.conf --config'
alias beats='python /home/ruin/build/beats_cli/beats_cli.py'
alias s='sudo $(fc -ln -1)'

# assuming EDITOR is empty, since dmenu_recent_aliases breaks on double quotes
alias e='emacsclient -t '
alias er='pkill emacs ; emacsclient -t '
alias ec='emacsclient -c -n '
alias ecr='pkill emacs ; emacsclient -c -n'
#alias vim='emacsclient -t '

alias git="hub"

alias E="SUDO_EDITOR=\"emacsclient -c -n\" sudoedit"

alias mpvm="mpv --profile=movie "
alias mpvd="mpv --profile=demo "
alias mpvp="mpv --profile=player "

alias sy='sudo systemctl'
alias usy='systemctl --user'
alias sr="surfraw google"
alias srl="surfraw google -l"
alias rsbk="RUST_BACKTRACE=1"
alias mkdir="mkdir -p"

alias in="at now + "
alias wttr="curl wttr.in/61820"
alias df="df -h"
alias lua="lua5.1"
