---
- hosts: webservers
  tasks:
      - name: add jenkins user
        user:
            name: jenkins
            group: jenkins
      - name: ensure github.com is a known host to jenkins
        become: yes
        become_user: "jenkins"
        lineinfile:
            dest: "/home/jenkins/.ssh/known_hosts"
            create: yes
            state: present
            line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
            regexp: "^github\\.com"
      - name: ensure jenkins SSH key is generated
        command: ssh-keygen -t rsa -f jenkins-id_rsa -N ''
        args:
            creates: jenkins-id_rsa
      - name: Set permissions for known_hosts
        become: yes
        file:
            path: "/home/jenkins/.ssh/known_hosts"
            owner: jenkins
            group: jenkins
            mode: 0600
      - name: Setup jenkins
        import_role:
            name: jenkins
        vars:
            jenkins_admin_password: jenkins
            jenkins_ssh_private_key: jenkins-id_rsa
            jenkins_ssh_public_key: jenkins-id_rsa.pub
            jenkins_git_user: git
            jenkins_git_host: github.com
            jenkins_git_path: git
            jenkins_git_repositories:
                - Ruin0x11/scribl
