directory: /mnt/hibiki/music/beets
per_disc_numbering: yes
import:
    copy: yes
    write: yes
    log: beets.log
    # duplicate_action: skip
    incremental_skip_later: yes
    incremental: no
plugins: copyartifacts ftintitle plexupdate fetchart importadded missing lyrics inline vocadb vgmdb # discogs
pluginpath:
  - /home/ruin/.config/beets/plugin/beets-vocadb
  - /home/ruin/.config/beets/plugin/VGMdb-BeetsPlug
ui:
    color: yes

paths:
    default: $albumartist/($year) $album%aunique{}/%if{$multidisc,Disc $disc/}$track. $title
    singleton: single/$artist - $title
    comp: compilation/$album%aunique{}/%if{$multidisc,Disc $disc/}$track. $artist - $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0

fetchart:
    cautious: true
    cover_names: front back
    sources: itunes coverart albumart amazon

plex:
    host: 192.168.1.100
    port: 32400
    library: 音楽
    token: ijwZwEoreT-ibGAjyyiq

importadded:
    preserve_mtimes: yes

missing:
    format: $albumartist - $album - $title
    count: yes
    total: yes

copyartifacts:
    print_ignored: yes

lyrics:
    sources: genius lyricwiki lyrics.com musixmatch
    auto: no

vgmdb:
    lang-priority: ja, ja-latn, en
