#!/bin/sh

if [ `xrandr | grep -c ' connected '` -eq 2 ]; then
    if [ `xrandr | grep HDMI1 | grep -c ' connected '` -eq 1 ]; then
        bspc monitor HDMI1 -n 0 -d 1 2 3 4
        bspc monitor eDP1 -n 1 -d 5 6 7 8
    fi
else
    bspc monitor -d 1 2 3 4
fi

bspc config border_width 3
bspc config -m focused border_width 3
bspc config window_gap              6
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     false
bspc config ignore_ewmh_focus       true
bspc config auto_cancel             true
bspc config auto_alternate          true


# SHADOWS ONLY WHEN FLOATING
# To use with shadow-exclude = [ "_BSPWM_FLOATING_WINDOW:32c = 0" ] in the compton.conf and with the richardgv-dev branch of compton
bspc config apply_floating_atom true


#
## COLORS ##
#

bspc config focused_border_color "#A73E28"
bspc config normal_border_color "#292825"
bspc config presel_border_color "#C2AD9D"
bspc config focused_sticky_border_color "#62712C"
bspc config normal_sticky_border_color "#3D444E"
bspc config focused_private_border_color "#9D534A"
bspc config normal_private_border_color "#9B7046"


#
## RULES ##
#

# Floating windows
bspc rule -a wine state=floating
bspc rule -a nitrogen state=floating
bspc rule -a fceux state=floating
bspc rule -a pcsx2 state=floating
bspc rule -a Java state=floating
bspc rule -a sun-awt-X11-XFramePeer state=floating
bspc rule -a meh state=floating center=on desktop=4

# Center floating window
bspc rule -a \* center=true

# habits
bspc rule -a emacs desktop=1
bspc rule -a chromium desktop=2

#
## MONOCLE ##
#

# Usually it's just emacs in the first workspace, chromium in the second. So, setup monocle for both.

bspc desktop 1 -l monocle
bspc desktop 2 -l monocle

#
## PANEL
#

# panel &

#
## APPS
#

# emacsclient -c -n &
# chromium &
