#! /bin/sh
if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Settings
. panel-settings
bspc config top_padding $height

# Time and wm info 
bspc subscribe > "$PANEL_FIFO" &
# clock -i 60 -sf "S%{B$bg_clock}  %{F$fg_squares} %{F$fg_clockemph}%d %{F$fg_clock}%b  %{F$fg_squares}%{F$fg_clock} %H:%M %{B-}%{F-}" > "$PANEL_FIFO" &
clock -i 60 -sf "S%{B$bg_clock}  %{F$fg_squares} %{F$fg_clockemph}%b %{F$fg_clock}%d日 %{F$fg_squares}%{F$fg_clock} %H:%M %{B-}%{F-}" > "$PANEL_FIFO" &

# Wallpaper
feh --bg-fill ~/Picture/wallhaven-64427.png &

# Make the panel
cat "$PANEL_FIFO" | panel-skeleton | lemonbar -a 100 -g x$height -B $bg_global -F $fg_global -f "$font2" -f "$font" | while read line; do eval "$line"; done &

# Mails and notifications
panel-mail &
panel-torrents &
not-stat Mu &
ns-ping &
while true
do
    mail-sync
    sleep 120
done &

wait
